# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3999fee52a7794e2e845e5e108b180b3417f4c467db458baf51a3d02b05c9e7d28414002b0800d1274b38e51c8186d3bca23b22979eed6f040df5749e6addaa5

test:
  secret_key_base: 85cc98fe135981884696b902df3daa1e883e3b26cc444acaea39a09b86973e751c6f87fcd10d4e648738050ea4c4e116c4206f315db950e2831dc53908ea76c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
